# Create model for prediction of gamma shower

## Load modules and data

In [ ]:
# import modules
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import pickle

from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline 

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, validation_curve, StratifiedKFold, cross_validate
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import f1_score, precision_score, recall_score, roc_curve, make_scorer
from sklearn.base import clone

import optuna 
from optuna.samplers import TPESampler
import time

from src.features import engineer_features

In [35]:
# ignore Data Conversion Warnings
from sklearn.exceptions import DataConversionWarning
import warnings
warnings.filterwarnings(action='ignore', category=DataConversionWarning)

In [36]:
# show three digits
pd.set_option('display.float_format', '{:,.3f}'.format)
pd.set_option('display.precision', 3)
np.set_printoptions(precision=3)

In [37]:
# set column names
columns = [
    "fLength",
    "fWidth",
    "fSize",
    "fConc",
    "fConc1",
    "fAsym",
    "fM3Long",
    "fM3Trans",
    "fAlpha",
    "fDist",
    "class"
]

# load data
df = pd.read_csv(
    r"../data/raw/magic04.data",
    header=None,
    names=columns
)

# remove dublicates before train-test-split
df = df.drop_duplicates().reset_index(drop=True)

# convert target from g/h --> 1/0
df["class"] = df["class"].map({
    "g": 1,   # gamma = signal
    "h": 0    # hadron = background
})

features = df.iloc[:, :-1]
target = df.iloc[:, -1]

features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.1, random_state=42)

In [38]:
display(target_train)

15421    0
6829     1
11808    1
7765     1
12077    1
        ..
11284    1
11964    1
5390     1
860      1
15795    0
Name: class, Length: 17014, dtype: int64

In [39]:
# save features_test as 'features_test.csv'
features_train.to_csv('../data/raw/features_train_unprocessed.csv', index=False)

In [40]:
# save target_train as 'target_train.csv'
target_train.to_csv('../data/raw/target_train_unprocessed.csv', index=False)

In [41]:
# save features_test as 'features_test.csv'
features_test.to_csv('../data/rawfeatures_test_unprocessed.csv', index=False)

In [42]:
# save target_test as 'target_test.csv'
target_test.to_csv('../data/raw/target_test_unprocessed.csv', index=False)

## Scoring
Bei dem gegebenen Datensatz ist die accuracy als Gütemaß nicht aussagekräftig. Eine Klassifizierung eines Backround-Events als Gamma-Event ist hier viel schwerwiegender als eine fälschliche Klassifizierung eines Gamma-Events als Backround-Events.
Hier kommt es besonders darauf an, für verschiedene Grenzwerte 0.01, 0.02, 0.05, 0.1 und 0.2 (je nach Experiment) für die Wahrscheinlichkeit ein Backround-Event als Signal zu klassifizieren einen möglichst hohen Wert bei der ROC-Curve zu erhalten. Sieht man ein Gamma-Ereignis als Klasse  1 und ein Backround-Event als Klasse 0 an, so ergibt FPR (False Positiv Rate) den Anteil der Hadron-Ereignisse an, die fälschlicherweise als Gamma klassifiziert werden und TRP (True Positiv Rate / Recall) den Anteil der Gamma-Ereignisse, die korrekt als Gama identifiziert werden. Für die jeweiligen Grenzwerte der FPR, soll also die TPR (also die gamma-Effiezienz) möglichst groß werden. 
Für dieses Projekt wird deshalb ein eigenes Scoring definiert.
Als primäre Auswahlmetrik wird hier 5% verwendet, die anderen Metriken werden jedoch zusätzlich betrachtet

In [43]:
# true positiv rate at a given false positive rate, 0.05 as default
def tpr_at_fpr(target, target_pred, max_fpr=0.05):
    fpr, tpr, _ = roc_curve(target, target_pred)

    return np.max(tpr[fpr <= max_fpr])

In [44]:
# define scorer for different thresholds of fpr
scoring = {
    "roc_auc": "roc_auc",

    "tpr_fpr_001": make_scorer(
        tpr_at_fpr,
        response_method=("decision_function", "predict_proba"),   # use continouus model-score, if decision_function not supportet, use predict_proba
        max_fpr=0.01
    ),

    "tpr_fpr_002": make_scorer(
        tpr_at_fpr,
        response_method=("decision_function", "predict_proba"),
        max_fpr=0.02
    ),

    "tpr_fpr_005": make_scorer(
        tpr_at_fpr,
        response_method=("decision_function", "predict_proba"),
        max_fpr=0.05
    ),

    "tpr_fpr_010": make_scorer(
        tpr_at_fpr,
        response_method=("decision_function", "predict_proba"),
        max_fpr=0.10
    ),

    "tpr_fpr_020": make_scorer(
        tpr_at_fpr,
        response_method=("decision_function", "predict_proba"),
        max_fpr=0.20
    )
}

In diesem Notebook wird zunächst nur der scorer "tpr_fpr_020" verwendet

## Data Preparation

### Datatype transformation

Es ist keine weitere Umwandlung der Trainingsdaten notwendig (Umwandlung Target g/h --> 1/0 siehe oben)

### Data Imputation

Der Datensatz beinhaltet keine fehlenden Werte, es müssen also keine Daten imputiert werden

### Outlier
Der verwendete Datensatz beinhaltet keine unplausiblen Ausreißer. Alle in der univariaten Betrachtung auftretenden extremen Werte werden im Datensatz belassen, da sie in der multivariaten Betrachtung nicht auffällig sind

### Clean_data function

In [45]:
def clean_data(target):
    """
    Input: target to be changed to classes 1/0
    Output: cleaned target
    """
    # convert target from g/h --> 1/0
    target = target.map({
    "g": 1,   # gamma = signal
    "h": 0    # hadron = background
    })
  
    
    return target

### set cross-validation-parameter
Im folgenden wird immer wieder auf diese Definition zurückgegriffen

In [46]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

### Resampling

Da die Zielklassen mit etwa 65% (g) zu 35% (h) leicht unausgegleichen sind, wird über eine Kreuzvalidierung mit GridSearch ermittelt, welches Verfahren für diesen Datensatz am geeignetsten für ein Resampling ist

In [47]:
selected_features = features_train.columns   # use all columns

strategies = [   # combination of strategy name, sampling method and class_weights

    # No treatment of class imbalance
    (
        "baseline",
        "passthrough",
        None
    ),

    # Randomly duplicate minority-class observations
    (
        "oversampling",
        RandomOverSampler(random_state=42),
        None
    ),

    # Randomly remove majority-class observations
    (
        "undersampling",
        RandomUnderSampler(random_state=42),
        None
    ),

    # Handle imbalance through Logistic Regression itself
    (
        "class_weights",
        "passthrough",
        "balanced"
    ),

    # Generate synthetic minority observations
    (
        "SMOTE",
        SMOTE(random_state=42),
        None
    )
]


# ------------------------------------------------------------
# Hyperparameter search space
# ------------------------------------------------------------

param_grid = {
    "estimator__C": [
        0.001,
        0.01,
        0.1,
        1,
        10,
        100
    ]
}


# ------------------------------------------------------------
# GridSearch for every imbalance strategy
# ------------------------------------------------------------

results = []

best_models = {}

for name, sampler, class_weight in strategies:

    sampling_pipeline = Pipeline([
        (
            "scaler",
            StandardScaler()
        ),
        (
            "sampler",
            sampler
        ),
        (
            "estimator",
            LogisticRegression(
                solver="lbfgs",
                class_weight=class_weight,
                max_iter=1000,
                random_state=42
            )
        )
    ])
    grid_search = GridSearchCV(estimator = sampling_pipeline,
                              param_grid = param_grid,
                               cv = cv,
                              scoring = scoring["tpr_fpr_020"],
                              n_jobs = -1)
    grid_search.fit(features_train, target_train)
    model = grid_search.best_estimator_.named_steps['estimator']
    print(name)
    print(f"{grid_search.scoring} on Validationset: {grid_search.best_score_:.3f}")
    print(model)
    print('#'*11)

baseline
make_scorer(tpr_at_fpr, response_method=('decision_function', 'predict_proba'), max_fpr=0.2) on Validationset: 0.724
LogisticRegression(C=0.001, max_iter=1000, random_state=42)
###########
oversampling
make_scorer(tpr_at_fpr, response_method=('decision_function', 'predict_proba'), max_fpr=0.2) on Validationset: 0.737
LogisticRegression(C=1, max_iter=1000, random_state=42)
###########
undersampling
make_scorer(tpr_at_fpr, response_method=('decision_function', 'predict_proba'), max_fpr=0.2) on Validationset: 0.735
LogisticRegression(C=0.01, max_iter=1000, random_state=42)
###########
class_weights
make_scorer(tpr_at_fpr, response_method=('decision_function', 'predict_proba'), max_fpr=0.2) on Validationset: 0.737
LogisticRegression(C=10, class_weight='balanced', max_iter=1000,
                   random_state=42)
###########
SMOTE
make_scorer(tpr_at_fpr, response_method=('decision_function', 'predict_proba'), max_fpr=0.2) on Validationset: 0.735
LogisticRegression(C=0.1, max_iter=1000, random_state=42)
###########

Für alle Verfahren (baseline ausgenommen), zeigt sich ein sehr ähnlicher Score. Der Einfachheit halber wird deshalb class_weights='balanced' verwendet

## Baseline model
Als Baseline Modell wird eine einfache logistische Regression mit allen 10 ursprünglichen Features und ohne Sampling verwendet

In [48]:
# select baseline features
baseline_features = [
    "fLength",
    "fWidth",
    "fSize",
    "fConc",
    "fConc1",
    "fAsym",
    "fM3Long",
    "fM3Trans",
    "fAlpha",
    "fDist"
]

In [49]:
# instantiate model
log_reg = LogisticRegression(
    max_iter=10000,
    random_state=42
)

In [50]:
# build pipeline
log_reg_bl = Pipeline(steps = [('scaler', StandardScaler()), 
                                ('model', log_reg)])

In [51]:
# validate baseline model
cv_log_reg = cross_val_score(estimator= log_reg_bl,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"])

print(f"CV best Score: {cv_log_reg.mean():.3f}")

CV best Score: 0.721

In [52]:
# fit pipeline 
log_reg_bl.fit(features_train, target_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model', LogisticRegression(max_iter=10000, random_state=42))])

In [53]:
pickle.dump(log_reg_bl, open('log_reg_bl.p', 'wb'))

## Feature Engineering
Wie in der EDA bereits vorgestellt, gibt es einige inteessante neue Features, die aus den alten Features erstellt werden können

In [54]:
# Betrag der symmetrischen Features
features_train["abs_fAsym"] = features_train["fAsym"].abs()
features_train["abs_fM3Long"] = features_train["fM3Long"].abs()
features_train["abs_fM3Trans"] = features_train["fM3Trans"].abs()

In [55]:
# Längen-/Breitenverhältnis
features_train["width_length_ratio"] = features_train["fWidth"] / features_train["fLength"]

In [56]:
# Größe der Hillas-Ellipse
features_train["ellipse_area"] = features_train["fLength"] * features_train["fWidth"] * np.pi

In [57]:
# wie stark dominiert das hellste Pixel die beiden hellsten Pixel
features_train["brightest_pixel_share"] = features_train["fConc1"] / features_train["fConc"]

In [58]:
# Umwandlung von alpha vom Wertebereich 0 bis 90 auf 0 bis 1, 1 entspricht perfekte Ausrichtung zum Kamerazentrum
features_train["alpha_alignment"] = np.cos(np.deg2rad(features_train["fAlpha"]))

In [59]:
features_train.shape

(17014, 17)

In [60]:
def engineer_features(df):
    """
    Input: DataFrame
    Output: Dataframe
    creates new features
    """
    df = df.copy()
    
    # Betrag der symmetrischen Features
    df["abs_fAsym"] = df["fAsym"].abs()
    df["abs_fM3Long"] = df["fM3Long"].abs()
    df["abs_fM3Trans"] = df["fM3Trans"].abs()

    # Längen-/Breitenverhältnis
    df["width_length_ratio"] = df["fWidth"] / df["fLength"]

    # Größe der Hillas-Ellipse
    df["ellipse_area"] = df["fLength"] * df["fWidth"] * np.pi

    # wie stark dominiert das hellste Pixel die beiden hellsten Pixel
    df["brightest_pixel_share"] = df["fConc1"] / df["fConc"]

    # Umwandlung von alpha vom Wertebereich 0 bis 90 auf 0 bis 1, 1 entspricht perfekte Ausrichtung zum Kamerazentrum
    df["alpha_alignment"] = np.cos(np.deg2rad(df["fAlpha"]))

    return(df)

## Scaling
Da das Scaling wird später in die Pipeline integriert und hier deshalb nur instanziiert

In [61]:
scaler = StandardScaler()

## Logistische Regression
Als erstes Modell wird die logistische Regression betrachtet, zunächst ohne PCA, dann mit PCA. Im Anschluss wird mittels Bayesian Optimization eine Optimierung der Hyperparameter vorgenommen

In [62]:
# build unoptimized model

# instantiate model
log_reg = LogisticRegression(
    solver="lbfgs",  
    max_iter=10000,
    random_state=42,
    class_weight='balanced', 
    n_jobs=-1
)


# Instantiating final pipeline with preprocessor and model (logreg)
log_reg_pipe = Pipeline(steps = [('scaler', StandardScaler()), 
                                ('model', log_reg)])

cv_log_reg = cross_val_score(estimator= log_reg_pipe,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)

print(f"CV Score: {cv_log_reg.mean():.3f}")

CV Score: 0.768

zum Vergleich Ergebnis des Baseline Modells: 0.721
Durch Hinzunahme der neu erstellten Features deutliche Verbesserung der Modellgüte

In [64]:
# build unoptimized model with PCA

# instantiate model
log_reg = LogisticRegression(
    solver="lbfgs",  
    max_iter=10000,
    random_state=42,
    class_weight='balanced', 
    n_jobs=-1
)


# Instantiating final pipeline with preprocessor and model (logreg)
log_reg_pipe_PCA = Pipeline(steps = [('scaler', StandardScaler()), 
                                 ('PCA', PCA(n_components=0.95, random_state=42)),
                                ('model', log_reg)])

# validate baseline model
cv_log_reg = cross_val_score(estimator= log_reg_pipe_PCA,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)

print(f"CV Score: {cv_log_reg.mean():.3f}")

CV Score: 0.717

zum Vergleich ohne PCA: 0.768
Durch Hinzunahme der PCA deutliche Verschlechterung der Modellgüte

In [65]:
# fit pipeline 
log_reg_pipe_PCA.fit(features_train, np.ravel(target_train))

c:\Users\moonp\Documents\Beruflich\Weiterbildung\Stackfuel - Data Science\Portfolio Projekt\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Pipeline(steps=[('scaler', StandardScaler()),
                ('PCA', PCA(n_components=0.95, random_state=42)),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=10000,
                                    n_jobs=-1, random_state=42))])

In [66]:
pickle.dump(log_reg_pipe_PCA, open('log_reg_PCA.p', 'wb'))

In [67]:
# instantiate model for optimization
log_reg = LogisticRegression(
    solver="liblinear",  
    max_iter=10000,
    random_state=42,
    class_weight='balanced', 
    n_jobs=-1
)

# Instantiating pipeline for optimization
log_reg_pipe_opt = Pipeline(steps = [('scaler', StandardScaler()), 
                                 ('pca', PCA()),
                                ('model', log_reg)])

In [77]:
# tune hyperparameters with Bayesian Optimization

def objective_log_reg(trial):

    
    print(f"\n========== Trial {trial.number} ==========")
    
    # search space
    C = trial.suggest_float("C", 1e-4, 1000, log=True)        # inverse of regularization strength (small --> simple model)
    l1_ratio = trial.suggest_categorical("l1_ratio", [0.0, 1.0])   # 
    n_components = trial.suggest_int("n_components", 1, 17)   # PCA

    
    params_log_reg = {'model__C': C,
            'model__l1_ratio': l1_ratio,
            'pca__n_components': n_components,
            'model__max_iter' : 10000
            }
    
    log_reg_pipe_opt.set_params(**params_log_reg)

    
    # initiating cv
    score_log_reg =  cross_val_score(estimator=log_reg_pipe_opt, 
                             X=features_train, 
                             y=target_train, 
                             scoring=scoring["tpr_fpr_020"],
                             cv=cv,
                             n_jobs=-1).mean()
    
    print(f"CV fertig: {score_log_reg:.4f}")
    
    return score_log_reg

# create a study (aim to maximize score) und setting a seed (random_state) for reproduceability
study_log_reg = optuna.create_study(sampler=TPESampler(seed = 42), direction='maximize')

# perform hyperparamter tuning (while timing the process)
time_start = time.time()
# starting optimization process with our defined function and 50 iterations
study_log_reg.optimize(objective_log_reg, n_trials=50)   # more trial took to long for time limit
time_bayesian = time.time() - time_start

# store result in a data frame 
values_bayesian_log_reg = [50, study_log_reg.best_trial.number, study_log_reg.best_trial.value, time_bayesian]
results_bayesian_log_reg = pd.DataFrame([values_bayesian_log_reg], columns = ['Number of iterations', 
                                                                        'Iteration Number of Optimal Hyperparamters', 
                                                                        'Score', 
                                                                        'Time Elapsed (s)'])

[I 2026-09-24 16:35:34,961] A new study created in memory with name: no-name-606ace7e-4095-491b-82eb-0c3d3cd8f6d8

========== Trial 0 ==========

[I 2026-09-24 16:35:35,328] Trial 0 finished with value: 0.7188974618058361 and parameters: {'C': 0.041858227295469716, 'l1_ratio': 0.0, 'n_components': 11}. Best is trial 0 with value: 0.7188974618058361.
[I 2026-09-24 16:35:35,536] Trial 1 finished with value: 0.7275275240481771 and parameters: {'C': 0.0012363188277052211, 'l1_ratio': 0.0, 'n_components': 15}. Best is trial 1 with value: 0.7275275240481771.

CV fertig: 0.7189

========== Trial 1 ==========
CV fertig: 0.7275

========== Trial 2 ==========

[I 2026-09-24 16:35:35,790] Trial 2 finished with value: 0.7678010670115593 and parameters: {'C': 1.6136341713591311, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 2 with value: 0.7678010670115593.
[I 2026-09-24 16:35:35,927] Trial 3 finished with value: 0.701546681755719 and parameters: {'C': 67.1581131106993, 'l1_ratio': 0.0, 'n_components': 4}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.7678

========== Trial 3 ==========
CV fertig: 0.7015

========== Trial 4 ==========

[I 2026-09-24 16:35:36,090] Trial 4 finished with value: 0.7026252121897987 and parameters: {'C': 0.013480180290890806, 'l1_ratio': 0.0, 'n_components': 5}. Best is trial 2 with value: 0.7678010670115593.
[I 2026-09-24 16:35:36,222] Trial 5 finished with value: 0.7046032252849406 and parameters: {'C': 1.918537370384187, 'l1_ratio': 1.0, 'n_components': 7}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.7026

========== Trial 5 ==========
CV fertig: 0.7046

========== Trial 6 ==========

[I 2026-09-24 16:35:36,400] Trial 6 finished with value: 0.7184485086088432 and parameters: {'C': 0.15577217702693022, 'l1_ratio': 0.0, 'n_components': 9}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.7184

========== Trial 7 ==========

[I 2026-09-24 16:35:36,605] Trial 7 finished with value: 0.6750264327863552 and parameters: {'C': 1.4024971326600353, 'l1_ratio': 1.0, 'n_components': 3}. Best is trial 2 with value: 0.7678010670115593.
[I 2026-09-24 16:35:36,811] Trial 8 finished with value: 0.6731394390105893 and parameters: {'C': 0.00028533901052402264, 'l1_ratio': 1.0, 'n_components': 14}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.6750

========== Trial 8 ==========
CV fertig: 0.6731

[I 2026-09-24 16:35:37,015] Trial 9 finished with value: 0.7177286395602619 and parameters: {'C': 0.013561145768453494, 'l1_ratio': 1.0, 'n_components': 8}. Best is trial 2 with value: 0.7678010670115593.

========== Trial 9 ==========
CV fertig: 0.7177

========== Trial 10 ==========

[I 2026-09-24 16:35:37,303] Trial 10 finished with value: 0.723301592433918 and parameters: {'C': 60.534049645042224, 'l1_ratio': 0.0, 'n_components': 14}. Best is trial 2 with value: 0.7678010670115593.
[I 2026-09-24 16:35:37,483] Trial 11 finished with value: 0.6957030555331016 and parameters: {'C': 0.0001805149711156605, 'l1_ratio': 0.0, 'n_components': 14}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.7233

========== Trial 11 ==========
CV fertig: 0.6957

========== Trial 12 ==========

[I 2026-09-24 16:35:37,727] Trial 12 finished with value: 0.7678010670115593 and parameters: {'C': 6.009961010249739, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 2 with value: 0.7678010670115593.

CV fertig: 0.7678

========== Trial 13 ==========

[I 2026-09-24 16:35:37,980] Trial 13 finished with value: 0.7678909950691133 and parameters: {'C': 1.9770982971146283, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 13 with value: 0.7678909950691133.
[I 2026-09-24 16:35:38,112] Trial 14 finished with value: 0.716560706490987 and parameters: {'C': 201.1175037285344, 'l1_ratio': 0.0, 'n_components': 10}. Best is trial 13 with value: 0.7678909950691133.

CV fertig: 0.7679

========== Trial 14 ==========
CV fertig: 0.7166

========== Trial 15 ==========

[I 2026-09-24 16:35:38,326] Trial 15 finished with value: 0.7678010670115593 and parameters: {'C': 36.10312376918297, 'l1_ratio': 1.0, 'n_components': 17}. Best is trial 13 with value: 0.7678909950691133.
[I 2026-09-24 16:35:38,459] Trial 16 finished with value: 0.7614181957804542 and parameters: {'C': 0.12117784756958887, 'l1_ratio': 1.0, 'n_components': 15}. Best is trial 13 with value: 0.7678909950691133.

CV fertig: 0.7678

========== Trial 16 ==========
CV fertig: 0.7614

========== Trial 17 ==========

[I 2026-09-24 16:35:38,600] Trial 17 finished with value: 0.7239310484196914 and parameters: {'C': 0.7108545134926506, 'l1_ratio': 0.0, 'n_components': 12}. Best is trial 13 with value: 0.7678909950691133.
[I 2026-09-24 16:35:38,737] Trial 18 finished with value: 0.7177286799773663 and parameters: {'C': 27.806571872010206, 'l1_ratio': 1.0, 'n_components': 11}. Best is trial 13 with value: 0.7678909950691133.

CV fertig: 0.7239

========== Trial 18 ==========
CV fertig: 0.7177

========== Trial 19 ==========

[I 2026-09-24 16:35:38,958] Trial 19 finished with value: 0.7624969283000567 and parameters: {'C': 0.02050983586493678, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 13 with value: 0.7678909950691133.

CV fertig: 0.7625

========== Trial 20 ==========

[I 2026-09-24 16:35:39,199] Trial 20 finished with value: 0.7684306038315414 and parameters: {'C': 699.2478748126686, 'l1_ratio': 0.0, 'n_components': 16}. Best is trial 20 with value: 0.7684306038315414.

CV fertig: 0.7684

========== Trial 21 ==========

[I 2026-09-24 16:35:39,459] Trial 21 finished with value: 0.7678909546520087 and parameters: {'C': 205.628995659351, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 20 with value: 0.7684306038315414.
[I 2026-09-24 16:35:39,647] Trial 22 finished with value: 0.7683407161910921 and parameters: {'C': 684.8971220683679, 'l1_ratio': 1.0, 'n_components': 16}. Best is trial 20 with value: 0.7684306038315414.

CV fertig: 0.7679

========== Trial 22 ==========
CV fertig: 0.7683

========== Trial 23 ==========

[I 2026-09-24 16:35:39,817] Trial 23 finished with value: 0.7232117047934685 and parameters: {'C': 299.8404237399103, 'l1_ratio': 1.0, 'n_components': 14}. Best is trial 20 with value: 0.7684306038315414.
[I 2026-09-24 16:35:39,949] Trial 24 finished with value: 0.723211502707946 and parameters: {'C': 1.3870123936557546, 'l1_ratio': 1.0, 'n_components': 13}. Best is trial 20 with value: 0.7684306038315414.

CV fertig: 0.7232

========== Trial 24 ==========
CV fertig: 0.7232

========== Trial 25 ==========

[I 2026-09-24 16:35:40,160] Trial 25 finished with value: 0.7622273057958129 and parameters: {'C': 6.365177104014377, 'l1_ratio': 0.0, 'n_components': 15}. Best is trial 20 with value: 0.7684306038315414.
[I 2026-09-24 16:35:40,315] Trial 26 finished with value: 0.7232114622908414 and parameters: {'C': 778.5902985898093, 'l1_ratio': 0.0, 'n_components': 13}. Best is trial 20 with value: 0.7684306038315414.

CV fertig: 0.7622

========== Trial 26 ==========
CV fertig: 0.7232

========== Trial 27 ==========

[I 2026-09-24 16:35:40,549] Trial 27 finished with value: 0.768520491471991 and parameters: {'C': 859.9521126161015, 'l1_ratio': 0.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:40,747] Trial 28 finished with value: 0.7683407161910921 and parameters: {'C': 647.3496565050298, 'l1_ratio': 1.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7685

========== Trial 28 ==========
CV fertig: 0.7683

========== Trial 29 ==========

[I 2026-09-24 16:35:40,896] Trial 29 finished with value: 0.70469311292539 and parameters: {'C': 102.57798705898942, 'l1_ratio': 1.0, 'n_components': 7}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:41,049] Trial 30 finished with value: 0.716560706490987 and parameters: {'C': 20.12481245168855, 'l1_ratio': 0.0, 'n_components': 10}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7047

========== Trial 30 ==========
CV fertig: 0.7166

========== Trial 31 ==========

[I 2026-09-24 16:35:41,295] Trial 31 finished with value: 0.7678010670115593 and parameters: {'C': 710.9637172393664, 'l1_ratio': 1.0, 'n_components': 17}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:41,502] Trial 32 finished with value: 0.7624970899684748 and parameters: {'C': 30.692119606421038, 'l1_ratio': 1.0, 'n_components': 15}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7678

========== Trial 32 ==========
CV fertig: 0.7625

[I 2026-09-24 16:35:41,638] Trial 33 finished with value: 0.7242007113410395 and parameters: {'C': 429.26044608955, 'l1_ratio': 1.0, 'n_components': 12}. Best is trial 27 with value: 0.768520491471991.

========== Trial 33 ==========
CV fertig: 0.7242

========== Trial 34 ==========

[I 2026-09-24 16:35:41,861] Trial 34 finished with value: 0.768340716191092 and parameters: {'C': 622.4132760120469, 'l1_ratio': 0.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7683

========== Trial 35 ==========
CV fertig: 0.7678

[I 2026-09-24 16:35:42,069] Trial 35 finished with value: 0.7678010670115593 and parameters: {'C': 130.8713268197811, 'l1_ratio': 1.0, 'n_components': 17}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:42,222] Trial 36 finished with value: 0.7624970899684748 and parameters: {'C': 822.2243769901656, 'l1_ratio': 1.0, 'n_components': 15}. Best is trial 27 with value: 0.768520491471991.

========== Trial 36 ==========
CV fertig: 0.7625

========== Trial 37 ==========

[I 2026-09-24 16:35:42,410] Trial 37 finished with value: 0.7683407161910921 and parameters: {'C': 3.834893235759843, 'l1_ratio': 1.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:42,553] Trial 38 finished with value: 0.7242007113410395 and parameters: {'C': 74.46011854985471, 'l1_ratio': 0.0, 'n_components': 12}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7683

========== Trial 38 ==========
CV fertig: 0.7242

========== Trial 39 ==========

[I 2026-09-24 16:35:42,805] Trial 39 finished with value: 0.7678909546520087 and parameters: {'C': 37.83840232520417, 'l1_ratio': 0.0, 'n_components': 17}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:42,950] Trial 40 finished with value: 0.716560706490987 and parameters: {'C': 338.37745383791486, 'l1_ratio': 1.0, 'n_components': 10}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7679

========== Trial 40 ==========
CV fertig: 0.7166

========== Trial 41 ==========

[I 2026-09-24 16:35:43,129] Trial 41 finished with value: 0.7674415568668661 and parameters: {'C': 0.07101869051192324, 'l1_ratio': 1.0, 'n_components': 17}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:43,294] Trial 42 finished with value: 0.723301592433918 and parameters: {'C': 216.14880907950587, 'l1_ratio': 0.0, 'n_components': 14}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7674

========== Trial 42 ==========
CV fertig: 0.7233

========== Trial 43 ==========

[I 2026-09-24 16:35:43,498] Trial 43 finished with value: 0.7683406757739875 and parameters: {'C': 2.0948995801094377, 'l1_ratio': 1.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:43,660] Trial 44 finished with value: 0.0 and parameters: {'C': 0.00015486652901998974, 'l1_ratio': 1.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7683

========== Trial 44 ==========
CV fertig: 0.0000

========== Trial 45 ==========

[I 2026-09-24 16:35:43,798] Trial 45 finished with value: 0.7152108964513783 and parameters: {'C': 0.0033200910948854457, 'l1_ratio': 1.0, 'n_components': 17}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:43,918] Trial 46 finished with value: 0.7251000727507881 and parameters: {'C': 0.00614344164578962, 'l1_ratio': 1.0, 'n_components': 15}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7152

========== Trial 46 ==========
CV fertig: 0.7251

========== Trial 47 ==========

[I 2026-09-24 16:35:44,068] Trial 47 finished with value: 0.723301592433918 and parameters: {'C': 8.147896715482602, 'l1_ratio': 1.0, 'n_components': 14}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7233

========== Trial 48 ==========

[I 2026-09-24 16:35:44,276] Trial 48 finished with value: 0.7684306038315414 and parameters: {'C': 81.43147353086842, 'l1_ratio': 0.0, 'n_components': 16}. Best is trial 27 with value: 0.768520491471991.
[I 2026-09-24 16:35:44,473] Trial 49 finished with value: 0.7622271441273947 and parameters: {'C': 1.6613380569504845, 'l1_ratio': 0.0, 'n_components': 15}. Best is trial 27 with value: 0.768520491471991.

CV fertig: 0.7684

========== Trial 49 ==========
CV fertig: 0.7622

In [78]:
# Ausgabe des Ergebnisses
results_bayesian_log_reg

,Number of iterations,Iteration Number of Optimal Hyperparamters,Score,Time Elapsed (s)
0,50,27,0.769,9.511

In [79]:
# Ausgabe der besten Parameter
study_log_reg.best_params

{'C': 859.9521126161015, 'l1_ratio': 0.0, 'n_components': 16}

In [81]:
best_params_log_reg = study_log_reg.best_params
log_reg_pipe_bo = log_reg_pipe_opt.set_params(
            model__C=best_params_log_reg["C"],
            model__l1_ratio=best_params_log_reg["l1_ratio"],
            pca__n_components=best_params_log_reg["n_components"]
)

In [82]:
cv_log_reg_bo = cross_val_score(estimator= log_reg_pipe_bo,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)
#print(cv_log_reg_bo.mean())
print(f"CV Score: {cv_log_reg_bo.mean():.3f}")

CV Score: 0.769

zum Vergleich ohne Optimierung ohne PCA: 0.768

ohne Optimierung mit PCA: 0.717

nur minimale Verbesserung durch Optimierung

In [83]:
log_reg_pipe_bo.fit(features_train, target_train)

c:\Users\moonp\Documents\Beruflich\Weiterbildung\Stackfuel - Data Science\Portfolio Projekt\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1435: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=16)),
                ('model',
                 LogisticRegression(C=859.9521126161015,
                                    class_weight='balanced', max_iter=10000,
                                    n_jobs=-1, random_state=42,
                                    solver='liblinear'))])

In [84]:
pickle.dump(log_reg_pipe_bo, open('log_reg_opt.p', 'wb'))

## Support Vektor Machine
In EDA mehrere nichtlineare Zusammenhänge entdeckt, deshalb SVM besonders interessant

In [88]:
svm_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC(
        kernel="rbf",
        random_state=42
    ))
])

In [89]:
cv_svm = cross_val_score(estimator= svm_pipe,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)

print(f"CV Score: {cv_log_reg.mean():.3f}")

CV Score: 0.717

Zum Vergleich Baseline Modell: 0.721
leichte Verschlechterung im Vergleich zum Baseline Modell

In [90]:
svm_pipe.fit(features_train, target_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', SVC(random_state=42))])

In [91]:
pickle.dump(svm_pipe, open('svm_simple.p', 'wb'))

In [93]:
svm_pipe_opt = Pipeline([
    ("scaler", StandardScaler()),
    ("pca", PCA()),
    ("model", SVC(
        kernel="rbf",
        random_state=42
    ))
])

In [96]:
# tune hyperparameters with Bayesian Optimization

def objective_svm(trial):

    
    print(f"\n========== Trial {trial.number} ==========")
    
    # search space
    C = trial.suggest_float("C", 1e-3, 1000, log=True)        # steuert Trade-Off zwischen einfacher Entscheidungsgrenze und möglichst wenig Trainingsfehlern
    gamma = trial.suggest_float("gamma", 1e-4, 1e1, log=True)   #  bestimmt wie lokal der Einfluss eines einzelnen Trainingspunkts ist
    n_components = trial.suggest_int("n_components", 1, 17)   # PCA  

    
    params_svm = {'model__C': C,
            'model__gamma': gamma,
            'pca__n_components': n_components,
            'model__max_iter' : 10000
            }
    
    svm_pipe_opt.set_params(**params_svm)

    
    # initiating cv
    score_svm =  cross_val_score(estimator=svm_pipe_opt, 
                             X=features_train, 
                             y=target_train, 
                             scoring=scoring["tpr_fpr_020"],
                             cv=cv,
                             n_jobs=-1).mean()
    
    print(f"CV fertig: {score_svm:.4f}")
    
    return score_svm

# create a study (aim to maximize score) und setting a seed (random_state) for reproduceability
study_svm = optuna.create_study(sampler=TPESampler(seed = 42), direction='maximize')

# perform hyperparamter tuning (while timing the process)
time_start = time.time()
# starting optimization process with our defined function and 50 iterations
study_svm.optimize(objective_svm, n_trials=50)   # more trial took to long for time limit
time_bayesian = time.time() - time_start

# store result in a data frame 
values_bayesian_svm = [50, study_svm.best_trial.number, study_svm.best_trial.value, time_bayesian]
results_bayesian_svm = pd.DataFrame([values_bayesian_svm], columns = ['Number of iterations', 
                                                                        'Iteration Number of Optimal Hyperparamters', 
                                                                        'Score', 
                                                                        'Time Elapsed (s)'])

[I 2026-09-25 08:44:02,041] A new study created in memory with name: no-name-1d5eb619-753d-4dea-8ff3-1a61b0c561af

========== Trial 0 ==========

[I 2026-09-25 08:44:22,308] Trial 0 finished with value: 0.8178714331905261 and parameters: {'C': 0.1767016940294795, 'gamma': 5.669849511478847, 'n_components': 13}. Best is trial 0 with value: 0.8178714331905261.

CV fertig: 0.8179

========== Trial 1 ==========

[I 2026-09-25 08:44:31,233] Trial 1 finished with value: 0.6851851911729043 and parameters: {'C': 3.907967156822881, 'gamma': 0.0006026889128682511, 'n_components': 3}. Best is trial 0 with value: 0.8178714331905261.

CV fertig: 0.6852

========== Trial 2 ==========

[I 2026-09-25 08:44:46,918] Trial 2 finished with value: 0.8211991350739634 and parameters: {'C': 0.002231010801867922, 'gamma': 2.1423021757741068, 'n_components': 11}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.8212

========== Trial 3 ==========

[I 2026-09-25 08:44:59,857] Trial 3 finished with value: 0.7568335219464878 and parameters: {'C': 17.71884735480682, 'gamma': 0.00012674255898937226, 'n_components': 17}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.7568

========== Trial 4 ==========

[I 2026-09-25 08:45:08,413] Trial 4 finished with value: 0.7781360035567051 and parameters: {'C': 98.77700294007911, 'gamma': 0.0011526449540315614, 'n_components': 4}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.7781

========== Trial 5 ==========

[I 2026-09-25 08:45:20,683] Trial 5 finished with value: 0.6950742058038962 and parameters: {'C': 0.012601639723276799, 'gamma': 0.0033205591037519565, 'n_components': 9}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.6951

========== Trial 6 ==========

[I 2026-09-25 08:45:32,064] Trial 6 finished with value: 0.7590790558564384 and parameters: {'C': 0.3905441275210791, 'gamma': 0.0028585493941961923, 'n_components': 11}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.7591

========== Trial 7 ==========

[I 2026-09-25 08:45:44,573] Trial 7 finished with value: 0.6463497696225042 and parameters: {'C': 0.006870101665590026, 'gamma': 0.0028888383623653178, 'n_components': 7}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.6463

========== Trial 8 ==========

[I 2026-09-25 08:45:53,724] Trial 8 finished with value: 0.7908142025705278 and parameters: {'C': 0.5450293694558254, 'gamma': 0.8431013932082461, 'n_components': 4}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.7908

========== Trial 9 ==========

[I 2026-09-25 08:46:07,289] Trial 9 finished with value: 0.28236262226174114 and parameters: {'C': 1.2173252504194043, 'gamma': 0.09163741808778776, 'n_components': 1}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.2824

========== Trial 10 ==========

[I 2026-09-25 08:46:22,016] Trial 10 finished with value: 0.6476096516045591 and parameters: {'C': 0.0017418301536324362, 'gamma': 3.448286794348852, 'n_components': 2}. Best is trial 2 with value: 0.8211991350739634.

CV fertig: 0.6476

========== Trial 11 ==========

[I 2026-09-25 08:46:48,994] Trial 11 finished with value: 0.8593142429876324 and parameters: {'C': 0.05272254971726053, 'gamma': 1.9061369877430585, 'n_components': 14}. Best is trial 11 with value: 0.8593142429876324.

CV fertig: 0.8593

========== Trial 12 ==========

[I 2026-09-25 08:47:02,319] Trial 12 finished with value: 0.9060601406515237 and parameters: {'C': 2.429928164818416, 'gamma': 0.3150253641280958, 'n_components': 15}. Best is trial 12 with value: 0.9060601406515237.

CV fertig: 0.9061

========== Trial 13 ==========

[I 2026-09-25 08:47:15,364] Trial 13 finished with value: 0.9025544014226821 and parameters: {'C': 0.343960007793184, 'gamma': 0.18389929816205444, 'n_components': 15}. Best is trial 12 with value: 0.9060601406515237.

CV fertig: 0.9026

========== Trial 14 ==========

[I 2026-09-25 08:47:27,119] Trial 14 finished with value: 0.898777665508043 and parameters: {'C': 5.7716750162739014, 'gamma': 0.3135909851490368, 'n_components': 13}. Best is trial 12 with value: 0.9060601406515237.

CV fertig: 0.8988

========== Trial 15 ==========

[I 2026-09-25 08:47:40,631] Trial 15 finished with value: 0.9064194487106942 and parameters: {'C': 0.8733879424731184, 'gamma': 0.3029454672697699, 'n_components': 17}. Best is trial 15 with value: 0.9064194487106942.

CV fertig: 0.9064

========== Trial 16 ==========

[I 2026-09-25 08:47:54,897] Trial 16 finished with value: 0.8086120362137258 and parameters: {'C': 0.02341051170181343, 'gamma': 0.033005090527517385, 'n_components': 17}. Best is trial 15 with value: 0.9064194487106942.

CV fertig: 0.8086

========== Trial 17 ==========

[I 2026-09-25 08:48:06,269] Trial 17 finished with value: 0.9082171611025787 and parameters: {'C': 6.70465206569755, 'gamma': 0.2074192088418172, 'n_components': 17}. Best is trial 17 with value: 0.9082171611025787.

CV fertig: 0.9082

========== Trial 18 ==========

[I 2026-09-25 08:48:16,838] Trial 18 finished with value: 0.9083079783364318 and parameters: {'C': 34.92418146251849, 'gamma': 0.11108527761953839, 'n_components': 17}. Best is trial 18 with value: 0.9083079783364318.

CV fertig: 0.9083

========== Trial 19 ==========

[I 2026-09-25 08:48:27,178] Trial 19 finished with value: 0.8154466090049309 and parameters: {'C': 113.24454304709094, 'gamma': 0.0996868220543728, 'n_components': 15}. Best is trial 18 with value: 0.9083079783364318.

CV fertig: 0.8154

========== Trial 20 ==========

[I 2026-09-25 08:48:53,278] Trial 20 finished with value: 0.8576052461401666 and parameters: {'C': 285.29725472402583, 'gamma': 1.42343803466473, 'n_components': 17}. Best is trial 18 with value: 0.9083079783364318.

CV fertig: 0.8576

========== Trial 21 ==========

[I 2026-09-25 08:49:18,838] Trial 21 finished with value: 0.8490651523724839 and parameters: {'C': 42.656464756298455, 'gamma': 1.8814784697837261, 'n_components': 14}. Best is trial 18 with value: 0.9083079783364318.

CV fertig: 0.8491

========== Trial 22 ==========

[I 2026-09-25 08:49:30,736] Trial 22 finished with value: 0.9097458976638914 and parameters: {'C': 39.23198725052983, 'gamma': 0.018203824396691222, 'n_components': 13}. Best is trial 22 with value: 0.9097458976638914.

CV fertig: 0.9097

========== Trial 23 ==========

[I 2026-09-25 08:49:42,215] Trial 23 finished with value: 0.850594373939051 and parameters: {'C': 38.99369512125251, 'gamma': 0.0217018329649958, 'n_components': 10}. Best is trial 22 with value: 0.9097458976638914.

CV fertig: 0.8506

========== Trial 24 ==========

[I 2026-09-25 08:49:53,688] Trial 24 finished with value: 0.9102851830894835 and parameters: {'C': 16.76975144155198, 'gamma': 0.011657528963937536, 'n_components': 17}. Best is trial 24 with value: 0.9102851830894835.

CV fertig: 0.9103

========== Trial 25 ==========

[I 2026-09-25 08:50:05,741] Trial 25 finished with value: 0.4885995877455339 and parameters: {'C': 991.230443181406, 'gamma': 0.009207424743031744, 'n_components': 17}. Best is trial 24 with value: 0.9102851830894835.

CV fertig: 0.4886

========== Trial 26 ==========

[I 2026-09-25 08:50:19,191] Trial 26 finished with value: 0.8861929916740763 and parameters: {'C': 2.736209882952849, 'gamma': 0.007118504140674008, 'n_components': 16}. Best is trial 24 with value: 0.9102851830894835.

CV fertig: 0.8862

========== Trial 27 ==========

[I 2026-09-25 08:50:32,901] Trial 27 finished with value: 0.8952730175410233 and parameters: {'C': 18.659329319642712, 'gamma': 0.005050343871629941, 'n_components': 15}. Best is trial 24 with value: 0.9102851830894835.

CV fertig: 0.8953

========== Trial 28 ==========

[I 2026-09-25 08:50:45,678] Trial 28 finished with value: 0.7066729447902352 and parameters: {'C': 597.8208530167503, 'gamma': 0.0037996240004692975, 'n_components': 11}. Best is trial 24 with value: 0.9102851830894835.

CV fertig: 0.7067

========== Trial 29 ==========

[I 2026-09-25 08:50:59,514] Trial 29 finished with value: 0.9154092636003558 and parameters: {'C': 31.22110840415006, 'gamma': 0.022056943578127004, 'n_components': 17}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.9154

========== Trial 30 ==========

[I 2026-09-25 08:51:13,970] Trial 30 finished with value: 0.9057895077196669 and parameters: {'C': 46.37347286818624, 'gamma': 0.02619748987831898, 'n_components': 14}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.9058

========== Trial 31 ==========

[I 2026-09-25 08:51:28,712] Trial 31 finished with value: 0.9063304502465444 and parameters: {'C': 58.672037094962896, 'gamma': 0.01862807805768355, 'n_components': 17}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.9063

========== Trial 32 ==========

[I 2026-09-25 08:51:45,576] Trial 32 finished with value: 0.8474481448549026 and parameters: {'C': 6.015045996846647, 'gamma': 0.11535612160716602, 'n_components': 9}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.8474

========== Trial 33 ==========

[I 2026-09-25 08:52:02,814] Trial 33 finished with value: 0.7223054724759519 and parameters: {'C': 237.45214634201392, 'gamma': 0.019253989735968806, 'n_components': 15}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.7223

========== Trial 34 ==========

[I 2026-09-25 08:52:19,946] Trial 34 finished with value: 0.9056107428663809 and parameters: {'C': 6.541686501908214, 'gamma': 0.015682633627718847, 'n_components': 13}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.9056

========== Trial 35 ==========

[I 2026-09-25 08:52:40,408] Trial 35 finished with value: 0.897969848840029 and parameters: {'C': 200.58149255484005, 'gamma': 0.0023300241459178555, 'n_components': 15}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.8980

========== Trial 36 ==========

[I 2026-09-25 08:53:05,187] Trial 36 finished with value: 0.8749559049389702 and parameters: {'C': 106.9865389645006, 'gamma': 0.0009836652672886598, 'n_components': 12}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.8750

========== Trial 37 ==========

[I 2026-09-25 08:53:38,698] Trial 37 finished with value: 0.7984546924258347 and parameters: {'C': 3.816348665215729, 'gamma': 0.0011217257319461487, 'n_components': 14}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.7985

========== Trial 38 ==========

[I 2026-09-25 08:54:03,240] Trial 38 finished with value: 0.5504310888367957 and parameters: {'C': 469.38714191266405, 'gamma': 0.06304858014467206, 'n_components': 17}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.5504

========== Trial 39 ==========

[I 2026-09-25 08:54:25,349] Trial 39 finished with value: 0.9113642389459219 and parameters: {'C': 5.279700421514012, 'gamma': 0.030213247175920166, 'n_components': 17}. Best is trial 29 with value: 0.9154092636003558.

CV fertig: 0.9114

========== Trial 40 ==========

[I 2026-09-25 08:54:50,958] Trial 40 finished with value: 0.9157685312424219 and parameters: {'C': 17.033881600712867, 'gamma': 0.04402725017995011, 'n_components': 16}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9158

========== Trial 41 ==========

[I 2026-09-25 08:55:11,590] Trial 41 finished with value: 0.9138812545469243 and parameters: {'C': 11.515319192189287, 'gamma': 0.028294610611206337, 'n_components': 16}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9139

========== Trial 42 ==========

[I 2026-09-25 08:55:30,693] Trial 42 finished with value: 0.9130723466170882 and parameters: {'C': 7.675062221030576, 'gamma': 0.03134589869956912, 'n_components': 17}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9131

========== Trial 43 ==========

[I 2026-09-25 08:55:55,110] Trial 43 finished with value: 0.9145100638590252 and parameters: {'C': 19.427405359181158, 'gamma': 0.04736766833723112, 'n_components': 14}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9145

========== Trial 44 ==========

[I 2026-09-25 08:56:24,995] Trial 44 finished with value: 0.9130718211947295 and parameters: {'C': 7.457801541397337, 'gamma': 0.05096658946841794, 'n_components': 13}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9131

========== Trial 45 ==========

[I 2026-09-25 08:56:58,009] Trial 45 finished with value: 0.8801697114218736 and parameters: {'C': 0.5146514736057909, 'gamma': 0.01493670303612556, 'n_components': 15}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.8802

========== Trial 46 ==========

[I 2026-09-25 08:57:24,167] Trial 46 finished with value: 0.8835847546681755 and parameters: {'C': 24.345492547430634, 'gamma': 0.23707161669587176, 'n_components': 14}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.8836

========== Trial 47 ==========

[I 2026-09-25 08:57:47,152] Trial 47 finished with value: 0.8960816425511278 and parameters: {'C': 1.1836318877809409, 'gamma': 0.016729327418665417, 'n_components': 17}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.8961

========== Trial 48 ==========

[I 2026-09-25 08:58:16,043] Trial 48 finished with value: 0.8472670358095546 and parameters: {'C': 31.125442360265122, 'gamma': 0.5547469927348738, 'n_components': 17}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.8473

========== Trial 49 ==========

[I 2026-09-25 08:58:44,396] Trial 49 finished with value: 0.9014756284859754 and parameters: {'C': 0.5930817921680726, 'gamma': 0.03905072959094763, 'n_components': 16}. Best is trial 40 with value: 0.9157685312424219.

CV fertig: 0.9015

In [97]:
# Ausgabe des Ergebnisses
results_bayesian_svm

,Number of iterations,Iteration Number of Optimal Hyperparamters,Score,Time Elapsed (s)
0,50,40,0.916,882.383

In [98]:
# Ausgabe der besten Parameter
study_svm.best_params

{'C': 17.033881600712867, 'gamma': 0.04402725017995011, 'n_components': 16}

In [ ]:
best_params_svm = study_svm.best_params
svm_pipe_bo = svm_pipe_opt.set_params(
            model__C=best_params_svm["C"],
            model__gamma=best_params_svm["gamma"],
            pca__n_components=best_params_svm["n_components"]
)

In [100]:
cv_svm_bo = cross_val_score(estimator= svm_pipe_bo,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)
#print(cv_log_reg_bo.mean())
print(f"CV Score: {cv_svm_bo.mean():.3f}")

CV Score: 0.916

Zum Vergleich ohne Optimierung: 0.717

optimiertes Logistische Regession-Modell: 0.769

Damit ist die optimierte Support Vektor Machine das bisher interessanteste Modell. Die Optimierung hat eine deutliche Verbesserung gegenüber dem einfachen Modell gebracht

In [ ]:
# fit optimized pipeline to trainset
svm_pipe_bo.fit(features_train, target_train)

c:\Users\moonp\Documents\Beruflich\Weiterbildung\Stackfuel - Data Science\Portfolio Projekt\.venv\Lib\site-packages\sklearn\svm\_base.py:337: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=16)),
                ('model',
                 SVC(C=17.033881600712867, gamma=0.04402725017995011,
                     max_iter=10000, random_state=42))])

In [102]:
# save optimized pipeline as pickle
pickle.dump(svm_pipe_bo, open('svm_opt.p', 'wb'))

## Random Forrest

In [105]:
# build unoptimized model

# instantiate model
model_rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=12,
    random_state=42,
    class_weight='balanced'
)


# Instantiating final pipeline, no need for scaling or PCA in RandomForest
rf_pipe = model_rf
cv_rf = cross_val_score(estimator= rf_pipe,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                           n_jobs=-1)
#print(cv_rf.mean())
print(f"CV Score: {cv_rf.mean():.3f}")

CV Score: 0.917

Zum Vergleich:
Baseline: 0.721
unoptimierte logostische Regression: 0.768
unoptimierte SVM: 0.717

In [ ]:
# fit pipeline to trainset
rf_pipe.fit(features_train, target_train)

RandomForestClassifier(class_weight='balanced', max_depth=12, random_state=42)

In [108]:
# save fitted pipeline as pickle
pickle.dump(rf_pipe, open('rf_simple.p', 'wb'))

In [ ]:
# optimize model with bayesian optimization
def objective_rf(trial):
    """return maximized f1-score"""
   
    # search space
    n_estimators = trial.suggest_int("n_estimators", 50, 250, step=50)
    max_depth = trial.suggest_int("max_depth", 5, 15)  
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10, step=2)   
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 3,10, step=1)   
    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2"])

    
    params_rf = {"n_estimators": n_estimators,
                'max_depth': max_depth,
              'min_samples_split': min_samples_split,
             'min_samples_leaf': min_samples_leaf,
              'max_features': max_features
            }
    rf_pipe.set_params(**params_rf)

    
    # initiating cv
    score_rf =  cross_val_score(estimator=rf_pipe, 
                             X=features_train, 
                             y=target_train, 
                             scoring=scoring["tpr_fpr_020"],
                             cv=cv,
                             n_jobs=-1).mean()
    
    return score_rf

# create a study (aim to maximize score) und setting a seed (random_state) for reproduceability
study_rf = optuna.create_study(sampler=TPESampler(seed = 42), direction='maximize')

# perform hyperparamter tuning (while timing the process)
time_start = time.time()
# starting optimization process with our defined function and 50 iterations
study_rf.optimize(objective_rf, n_trials=50)
time_bayesian = time.time() - time_start

# store result in a data frame 
values_bayesian_rf = [50, study_rf.best_trial.number, study_rf.best_trial.value, time_bayesian]
results_bayesian_rf = pd.DataFrame([values_bayesian_rf], columns = ['Number of iterations', 
                                                                        'Iteration Number of Optimal Hyperparamters', 
                                                                        'Score', 
                                                                        'Time Elapsed (s)'])

[I 2026-09-25 09:31:50,355] A new study created in memory with name: no-name-7b45eeb8-612d-4be4-a98e-5667b7cd2e18
[I 2026-09-25 09:31:59,330] Trial 0 finished with value: 0.9206230296661548 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:04,179] Trial 1 finished with value: 0.9170266348718779 and parameters: {'n_estimators': 50, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:15,120] Trial 2 finished with value: 0.8833142429876324 and parameters: {'n_estimators': 250, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:21,614] Trial 3 finished with value: 0.8951805432058848 and parameters: {'n_estimators': 150, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:29,813] Trial 4 finished with value: 0.9197239107590331 and parameters: {'n_estimators': 150, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:36,641] Trial 5 finished with value: 0.861649704955137 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:40,146] Trial 6 finished with value: 0.8590425996281628 and parameters: {'n_estimators': 100, 'max_depth': 6, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:43,473] Trial 7 finished with value: 0.9168470616765015 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:32:49,159] Trial 8 finished with value: 0.882325357691375 and parameters: {'n_estimators': 150, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.9206230296661548.
[I 2026-09-25 09:33:02,026] Trial 9 finished with value: 0.9217016409344435 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 9 with value: 0.9217016409344435.
[I 2026-09-25 09:33:26,555] Trial 10 finished with value: 0.9199038072912457 and parameters: {'n_estimators': 250, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 9 with value: 0.9217016409344435.
[I 2026-09-25 09:33:42,458] Trial 11 finished with value: 0.9236794115269582 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.9236794115269582.
[I 2026-09-25 09:34:03,169] Trial 12 finished with value: 0.9215220273219625 and parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.9236794115269582.
[I 2026-09-25 09:34:08,393] Trial 13 finished with value: 0.9237694204187212 and parameters: {'n_estimators': 50, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:34:18,046] Trial 14 finished with value: 0.9219713038557918 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:34:23,698] Trial 15 finished with value: 0.9218815778837604 and parameters: {'n_estimators': 50, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:34:44,942] Trial 16 finished with value: 0.9202633982701478 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:34:50,018] Trial 17 finished with value: 0.9204426077115835 and parameters: {'n_estimators': 50, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:35:09,356] Trial 18 finished with value: 0.9204432543852559 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 13 with value: 0.9237694204187212.
[I 2026-09-25 09:35:22,901] Trial 19 finished with value: 0.9253876000323336 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:35:33,787] Trial 20 finished with value: 0.9249379597445639 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:35:42,378] Trial 21 finished with value: 0.9222412496968717 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:35:46,713] Trial 22 finished with value: 0.9242187373696549 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:35:55,458] Trial 23 finished with value: 0.9225104276129658 and parameters: {'n_estimators': 100, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:36:03,573] Trial 24 finished with value: 0.9172060463988359 and parameters: {'n_estimators': 100, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:36:15,715] Trial 25 finished with value: 0.9213418478700186 and parameters: {'n_estimators': 150, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:36:29,077] Trial 26 finished with value: 0.9253876000323336 and parameters: {'n_estimators': 150, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:36:44,825] Trial 27 finished with value: 0.919633578530434 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 19 with value: 0.9253876000323336.
[I 2026-09-25 09:36:57,706] Trial 28 finished with value: 0.9257468676743998 and parameters: {'n_estimators': 150, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 28 with value: 0.9257468676743998.
[I 2026-09-25 09:37:10,861] Trial 29 finished with value: 0.9257468676743998 and parameters: {'n_estimators': 150, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 28 with value: 0.9257468676743998.
[I 2026-09-25 09:37:22,157] Trial 30 finished with value: 0.9177458976638914 and parameters: {'n_estimators': 150, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 28 with value: 0.9257468676743998.
[I 2026-09-25 09:37:37,746] Trial 31 finished with value: 0.9205328591059736 and parameters: {'n_estimators': 200, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 28 with value: 0.9257468676743998.
[I 2026-09-25 09:37:50,673] Trial 32 finished with value: 0.9231401261013661 and parameters: {'n_estimators': 150, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 28 with value: 0.9257468676743998.
[I 2026-09-25 09:38:08,146] Trial 33 finished with value: 0.9258369574003718 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 33 with value: 0.9258369574003718.
[I 2026-09-25 09:38:25,619] Trial 34 finished with value: 0.9269155686686605 and parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:38:42,110] Trial 35 finished with value: 0.9244888448791528 and parameters: {'n_estimators': 200, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:39:03,705] Trial 36 finished with value: 0.9258367148977447 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:39:25,928] Trial 37 finished with value: 0.921791528574893 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:39:47,766] Trial 38 finished with value: 0.9195442567294478 and parameters: {'n_estimators': 250, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:40:03,539] Trial 39 finished with value: 0.9258369574003718 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:40:18,730] Trial 40 finished with value: 0.9242186161183413 and parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:40:26,809] Trial 41 finished with value: 0.9262862339342008 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:40:46,757] Trial 42 finished with value: 0.9258367148977447 and parameters: {'n_estimators': 250, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:41:02,365] Trial 43 finished with value: 0.9258369574003718 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:41:18,129] Trial 44 finished with value: 0.9258369574003718 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:41:35,886] Trial 45 finished with value: 0.9215220273219625 and parameters: {'n_estimators': 200, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:41:44,682] Trial 46 finished with value: 0.9222412496968717 and parameters: {'n_estimators': 100, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:42:03,059] Trial 47 finished with value: 0.9228703419287042 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:42:07,732] Trial 48 finished with value: 0.9190946164416781 and parameters: {'n_estimators': 50, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.
[I 2026-09-25 09:42:26,065] Trial 49 finished with value: 0.9258369574003718 and parameters: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 34 with value: 0.9269155686686605.

In [110]:
# Ausgabe des Ergebnisses
results_bayesian_rf

,Number of iterations,Iteration Number of Optimal Hyperparamters,Score,Time Elapsed (s)
0,50,34,0.927,635.701

In [111]:
# Ausgabe der besten Parameter
study_rf.best_params

{'n_estimators': 200,
 'max_depth': 14,
 'min_samples_split': 2,
 'min_samples_leaf': 3,
 'max_features': 'log2'}

In [113]:
best_params_rf = study_rf.best_params
rf_pipe_bo = rf_pipe.set_params(
            n_estimators=best_params_rf["n_estimators"],
            max_depth=best_params_rf["max_depth"],
            min_samples_split=best_params_rf["min_samples_split"],
            min_samples_leaf=best_params_rf["min_samples_leaf"],
            max_features=best_params_rf["max_features"]
)

In [114]:
cv_rf_bo = cross_val_score(estimator= rf_pipe_bo,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)
#print(cv_log_reg_bo.mean())
print(f"CV Score: {cv_rf_bo.mean():.3f}")

CV Score: 0.927

Zum Vergleich: 

RandomForest ohne Optimierung: 0.917

optimierte logistische Regression: 0.769

optminierte SVM: 0.916

leichte Verbesserung gegenüber unoptimiertem Modell und optimierter SVM, bisher bestes Modell

## Einfaches neuronales Netz 
Für eher kleineren Datensatz wird zunächst einfaches neuronales Netz aus sklearn verwendet, um zu prüfen, ob ein neuronales Netz für dieses Projekt vielversprechend ist

In [120]:
# build unoptimized model

# instantiate model
model_nn = MLPClassifier(
        hidden_layer_sizes=(32, 16),   # zwei hidden layer, 1. mit  32 dann mit 16 
        activation="relu",             # acivation function
        solver="adam",
        alpha=1e-4,                    # L2 Regularisierung
        learning_rate_init=1e-3,       # anfängliche Schrittweite
        max_iter=500,
        early_stopping=True,
        validation_fraction=0.15,
        n_iter_no_change=20,
        random_state=42
    )



nn_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", model_nn)
])

cv_nn = cross_val_score(estimator= nn_pipe,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                           n_jobs=-1)

print(f"CV Score: {cv_nn.mean():.3f}")

CV Score: 0.904

Zum Vergleich: 

Baseline: 0.721

unoptimierte logistiche Regression: 0.768

unoptimierte SVM: 0.717

unoptimierter RandomForest: 0.917

In [121]:
# fit pipeline to trainset
nn_pipe.fit(features_train, target_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 MLPClassifier(early_stopping=True, hidden_layer_sizes=(32, 16),
                               max_iter=500, n_iter_no_change=20,
                               random_state=42, validation_fraction=0.15))])

In [122]:
# save fitted pipeline as pickle
pickle.dump(nn_pipe, open('nn_simple.p', 'wb'))

In [136]:
# optimize model with bayesian optimization
architectures = {
        "16": (16,),
        "32": (32,),
        "64": (64,),
        "32_16": (32, 16),
        "64_32": (64, 32),
        "64_32_16": (64, 32, 16)
}


def objective_nn(trial):
    """return maximized score"""


    architecture_name = trial.suggest_categorical(
        "architecture",
        list(architectures.keys())
    )
    
   
    # search space
    hidden_layer_sizes = architectures[architecture_name]
    alpha = trial.suggest_float("alpha", 1e-6, 1e-2, log=True)  
    learning_rate_init = trial.suggest_float("learning_rate_init", 1e-4, 1e-2, log=True)   
    activation = trial.suggest_categorical("activation", ["relu", "tanh"])  

    
    params_nn = {"model__hidden_layer_sizes": hidden_layer_sizes,
                'model__alpha': alpha,
              'model__learning_rate_init': learning_rate_init,
             'model__activation': activation  
            }
    nn_pipe.set_params(**params_nn)

    
    # initiating cv
    score_nn =  cross_val_score(estimator=nn_pipe, 
                             X=features_train, 
                             y=target_train, 
                             scoring=scoring["tpr_fpr_020"],
                             cv=cv,
                             n_jobs=-1).mean()
    
    return score_nn

# create a study (aim to maximize score) und setting a seed (random_state) for reproduceability
study_nn = optuna.create_study(sampler=TPESampler(seed = 42), direction='maximize')

# perform hyperparamter tuning (while timing the process)
time_start = time.time()
# starting optimization process with our defined function and 50 iterations
study_nn.optimize(objective_nn, n_trials=50)
time_bayesian = time.time() - time_start

# store result in a data frame 
values_bayesian_nn = [50, study_nn.best_trial.number, study_nn.best_trial.value, time_bayesian]
results_bayesian_nn = pd.DataFrame([values_bayesian_nn], columns = ['Number of iterations', 
                                                                        'Iteration Number of Optimal Hyperparamters', 
                                                                        'Score', 
                                                                        'Time Elapsed (s)'])

[I 2026-09-25 11:19:40,998] A new study created in memory with name: no-name-65c78519-ee7e-4cbc-b424-313d634902e7

[I 2026-09-25 11:19:50,388] Trial 0 finished with value: 0.8978794357772208 and parameters: {'architecture': '32', 'alpha': 1.7073967431528114e-06, 'learning_rate_init': 0.005399484409787433, 'activation': 'tanh'}. Best is trial 0 with value: 0.8978794357772208.
[I 2026-09-25 11:19:59,699] Trial 1 finished with value: 0.903902190607065 and parameters: {'architecture': '32', 'alpha': 1.6480446427978994e-05, 'learning_rate_init': 0.0011207606211860567, 'activation': 'relu'}. Best is trial 1 with value: 0.903902190607065.
[I 2026-09-25 11:20:04,730] Trial 2 finished with value: 0.9081283243068465 and parameters: {'architecture': '64_32_16', 'alpha': 6.290644294586145e-06, 'learning_rate_init': 0.0010677482709481358, 'activation': 'relu'}. Best is trial 2 with value: 0.9081283243068465.
[I 2026-09-25 11:20:12,253] Trial 3 finished with value: 0.9023739794681109 and parameters: {'architecture': '64_32', 'alpha': 1.6536937182824424e-05, 'learning_rate_init': 0.0001567993391672301, 'activation': 'relu'}. Best is trial 2 with value: 0.9081283243068465.
[I 2026-09-25 11:20:16,835] Trial 4 finished with value: 0.9083960067900737 and parameters: {'architecture': '32_16', 'alpha': 1.7654048052495086e-05, 'learning_rate_init': 0.001096821720752952, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:23,550] Trial 5 finished with value: 0.8671341443698972 and parameters: {'architecture': '16', 'alpha': 2.259279742015697e-06, 'learning_rate_init': 0.0002465844721448739, 'activation': 'tanh'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:26,332] Trial 6 finished with value: 0.89760957077035 and parameters: {'architecture': '64', 'alpha': 3.6618192203924288e-06, 'learning_rate_init': 0.0040215545266902904, 'activation': 'tanh'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:32,334] Trial 7 finished with value: 0.891945921914154 and parameters: {'architecture': '32_16', 'alpha': 0.0012164139351417069, 'learning_rate_init': 0.00014063366777718192, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:35,177] Trial 8 finished with value: 0.8893391399240158 and parameters: {'architecture': '16', 'alpha': 0.000828752236376816, 'learning_rate_init': 0.0018841476921545091, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:42,504] Trial 9 finished with value: 0.9025544014226821 and parameters: {'architecture': '64_32', 'alpha': 0.00012329098365270507, 'learning_rate_init': 0.0007162786999897341, 'activation': 'tanh'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:45,317] Trial 10 finished with value: 0.907318810120443 and parameters: {'architecture': '32_16', 'alpha': 7.821846444899149e-05, 'learning_rate_init': 0.0039847052128158, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:51,236] Trial 11 finished with value: 0.9052511518874787 and parameters: {'architecture': '64_32_16', 'alpha': 3.4888024127361557e-06, 'learning_rate_init': 0.00038669834036802477, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:20:58,482] Trial 12 finished with value: 0.9006666397219302 and parameters: {'architecture': '64_32_16', 'alpha': 2.61308351727818e-05, 'learning_rate_init': 0.001544794642622167, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:09,439] Trial 13 finished with value: 0.9047115431250505 and parameters: {'architecture': '64_32_16', 'alpha': 7.272300370928441e-05, 'learning_rate_init': 0.00030326896853147267, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:14,860] Trial 14 finished with value: 0.8982382588311373 and parameters: {'architecture': '32_16', 'alpha': 5.8136146332750525e-06, 'learning_rate_init': 0.0006844717635105973, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:22,069] Trial 15 finished with value: 0.9015653948751112 and parameters: {'architecture': '32_16', 'alpha': 0.0005677567864941853, 'learning_rate_init': 0.0005259784979750965, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:28,649] Trial 16 finished with value: 0.9067787567698649 and parameters: {'architecture': '64_32_16', 'alpha': 2.3179747483772375e-06, 'learning_rate_init': 0.00459471639859264, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:35,727] Trial 17 finished with value: 0.9070487026109448 and parameters: {'architecture': '64', 'alpha': 1.4925784182633051e-05, 'learning_rate_init': 0.004524435126986143, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:44,165] Trial 18 finished with value: 0.9029129011397623 and parameters: {'architecture': '32', 'alpha': 1.5643538085880278e-06, 'learning_rate_init': 0.0010012200416806899, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:50,837] Trial 19 finished with value: 0.8964412739471346 and parameters: {'architecture': '64_32_16', 'alpha': 1.1734482185873615e-05, 'learning_rate_init': 0.008567493455020647, 'activation': 'tanh'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:21:57,807] Trial 20 finished with value: 0.904172136448145 and parameters: {'architecture': '32_16', 'alpha': 1.1120692476524077e-06, 'learning_rate_init': 0.002704396439596665, 'activation': 'relu'}. Best is trial 4 with value: 0.9083960067900737.
[I 2026-09-25 11:22:03,995] Trial 21 finished with value: 0.9084865815212998 and parameters: {'architecture': '32_16', 'alpha': 1.3865718334212124e-05, 'learning_rate_init': 0.00958971779992218, 'activation': 'relu'}. Best is trial 21 with value: 0.9084865815212998.
[I 2026-09-25 11:22:09,163] Trial 22 finished with value: 0.909475749737289 and parameters: {'architecture': '32_16', 'alpha': 5.31907693671042e-06, 'learning_rate_init': 0.0029938713305203107, 'activation': 'relu'}. Best is trial 22 with value: 0.909475749737289.
[I 2026-09-25 11:22:14,996] Trial 23 finished with value: 0.9076781585967181 and parameters: {'architecture': '32_16', 'alpha': 0.0005342086344147978, 'learning_rate_init': 0.007400281936462041, 'activation': 'relu'}. Best is trial 22 with value: 0.909475749737289.
[I 2026-09-25 11:22:20,996] Trial 24 finished with value: 0.905430240077601 and parameters: {'architecture': '32_16', 'alpha': 6.822254528584771e-06, 'learning_rate_init': 0.0035794278365988775, 'activation': 'relu'}. Best is trial 22 with value: 0.909475749737289.
[I 2026-09-25 11:22:27,669] Trial 25 finished with value: 0.8994070810767116 and parameters: {'architecture': '32_16', 'alpha': 4.224785716560959e-05, 'learning_rate_init': 0.0009462308367698926, 'activation': 'relu'}. Best is trial 22 with value: 0.909475749737289.
[I 2026-09-25 11:22:35,505] Trial 26 finished with value: 0.9101943254385256 and parameters: {'architecture': '64', 'alpha': 3.2749259769938568e-06, 'learning_rate_init': 0.001953781302655148, 'activation': 'relu'}. Best is trial 26 with value: 0.9101943254385256.
[I 2026-09-25 11:22:41,317] Trial 27 finished with value: 0.9030030716999434 and parameters: {'architecture': '64', 'alpha': 9.336745618222695e-06, 'learning_rate_init': 0.0020483278577680827, 'activation': 'relu'}. Best is trial 26 with value: 0.9101943254385256.
[I 2026-09-25 11:22:46,551] Trial 28 finished with value: 0.9114529140732358 and parameters: {'architecture': '64', 'alpha': 1.4508998704639273e-06, 'learning_rate_init': 0.006886680986583811, 'activation': 'relu'}. Best is trial 28 with value: 0.9114529140732358.
[I 2026-09-25 11:22:56,409] Trial 29 finished with value: 0.9021042357125536 and parameters: {'architecture': '64', 'alpha': 1.7341896903018532e-06, 'learning_rate_init': 0.0016028773610804936, 'activation': 'tanh'}. Best is trial 28 with value: 0.9114529140732358.
[I 2026-09-25 11:23:02,712] Trial 30 finished with value: 0.9083074124969688 and parameters: {'architecture': '64', 'alpha': 1.4225479723652405e-06, 'learning_rate_init': 0.007622622007092274, 'activation': 'relu'}. Best is trial 28 with value: 0.9114529140732358.
[I 2026-09-25 11:23:08,612] Trial 31 finished with value: 0.9071376202408861 and parameters: {'architecture': '64', 'alpha': 6.921951715891426e-06, 'learning_rate_init': 0.007062256760776985, 'activation': 'relu'}. Best is trial 28 with value: 0.9114529140732358.
[I 2026-09-25 11:23:13,919] Trial 32 finished with value: 0.9134305229973325 and parameters: {'architecture': '32_16', 'alpha': 4.188431608057365e-06, 'learning_rate_init': 0.009550730208433559, 'activation': 'relu'}. Best is trial 32 with value: 0.9134305229973325.
[I 2026-09-25 11:23:19,134] Trial 33 finished with value: 0.9028228114137905 and parameters: {'architecture': '32_16', 'alpha': 5.151083359402799e-06, 'learning_rate_init': 0.0072568763335636895, 'activation': 'tanh'}. Best is trial 32 with value: 0.9134305229973325.
[I 2026-09-25 11:23:24,910] Trial 34 finished with value: 0.908126869291084 and parameters: {'architecture': '64', 'alpha': 2.423814479275004e-06, 'learning_rate_init': 0.002238053783108699, 'activation': 'relu'}. Best is trial 32 with value: 0.9134305229973325.
[I 2026-09-25 11:23:30,516] Trial 35 finished with value: 0.9095647886185434 and parameters: {'architecture': '32_16', 'alpha': 3.2378977295549087e-06, 'learning_rate_init': 0.009770683383443998, 'activation': 'relu'}. Best is trial 32 with value: 0.9134305229973325.
[I 2026-09-25 11:23:36,365] Trial 36 finished with value: 0.9134307654999596 and parameters: {'architecture': '32', 'alpha': 4.314125869757452e-05, 'learning_rate_init': 0.006015050910243471, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:23:42,656] Trial 37 finished with value: 0.9101050844717484 and parameters: {'architecture': '32', 'alpha': 0.00027381066047383186, 'learning_rate_init': 0.002445338508210995, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:23:47,977] Trial 38 finished with value: 0.9009352517985612 and parameters: {'architecture': '32_16', 'alpha': 4.817892982859092e-05, 'learning_rate_init': 0.007960275998804932, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:23:54,631] Trial 39 finished with value: 0.906148694527524 and parameters: {'architecture': '64', 'alpha': 1.2114376368438404e-06, 'learning_rate_init': 0.004084972245677132, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:00,621] Trial 40 finished with value: 0.9077678845687496 and parameters: {'architecture': '32_16', 'alpha': 3.3856241584849416e-06, 'learning_rate_init': 0.005707719486051123, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:07,862] Trial 41 finished with value: 0.9082167973486379 and parameters: {'architecture': '32', 'alpha': 0.0026939091537373397, 'learning_rate_init': 0.0024388267437222477, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:16,201] Trial 42 finished with value: 0.8989582087139277 and parameters: {'architecture': '32', 'alpha': 0.00378730496970028, 'learning_rate_init': 0.0007497628547400165, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:22,453] Trial 43 finished with value: 0.908667245978498 and parameters: {'architecture': '32', 'alpha': 0.0001860251986058554, 'learning_rate_init': 0.005167731642057647, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:32,306] Trial 44 finished with value: 0.9061497453722416 and parameters: {'architecture': '32', 'alpha': 4.657994934648586e-06, 'learning_rate_init': 0.0014777812908675144, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:41,276] Trial 45 finished with value: 0.899856600113168 and parameters: {'architecture': '64', 'alpha': 2.92396263577724e-06, 'learning_rate_init': 0.000912356513292923, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:24:53,305] Trial 46 finished with value: 0.901744078894188 and parameters: {'architecture': '32', 'alpha': 0.0002468517107130418, 'learning_rate_init': 0.0012451032574309032, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:25:05,786] Trial 47 finished with value: 0.904621412981974 and parameters: {'architecture': '32_16', 'alpha': 0.00011052977760613798, 'learning_rate_init': 0.0019165540374244216, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:25:18,358] Trial 48 finished with value: 0.9117229003314202 and parameters: {'architecture': '32', 'alpha': 4.523339776454827e-05, 'learning_rate_init': 0.003031267660836065, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.
[I 2026-09-25 11:25:30,675] Trial 49 finished with value: 0.8993171530191578 and parameters: {'architecture': '32', 'alpha': 7.31823345216019e-05, 'learning_rate_init': 0.0013561721379632273, 'activation': 'relu'}. Best is trial 36 with value: 0.9134307654999596.

In [140]:
# Ausgabe des Ergebnisses
results_bayesian_nn

,Number of iterations,Iteration Number of Optimal Hyperparamters,Score,Time Elapsed (s)
0,50,36,0.913,349.652

In [141]:
# Ausgabe der besten Parameter
study_nn.best_params

{'architecture': '32',
 'alpha': 4.314125869757452e-05,
 'learning_rate_init': 0.006015050910243471,
 'activation': 'relu'}

In [143]:
best_params_nn = study_nn.best_params

best_hidden_layer_sizes = architectures[
    best_params_nn["architecture"]
]

nn_pipe_bo = nn_pipe.set_params(
            model__hidden_layer_sizes=best_hidden_layer_sizes,
            model__alpha=best_params_nn["alpha"],
            model__learning_rate_init=best_params_nn["learning_rate_init"],
            model__activation=best_params_nn["activation"]
)

In [144]:
cv_nn_bo = cross_val_score(estimator= nn_pipe_bo,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)
#print(cv_log_reg_bo.mean())
print(f"CV Score: {cv_nn_bo.mean():.3f}")

CV Score: 0.913

Zum Vergleich: 

neuronales Netz ohne Optimierung: 0.904

optimierte logistische Regression: 0.769

optminierte SVM: 0.916

optimierter RandomForest: 0.927

optimierter RandomForest bisher bestes Modell

In [146]:
# optimize model with bayesian optimization
def objective_rf_2(trial):
    """return maximized f1-score"""
   
    # search space
    n_estimators = trial.suggest_int("n_estimators", 300, 1500, step=100)
    max_depth = trial.suggest_int("max_depth", 4, 30)  
    min_samples_split = trial.suggest_int("min_samples_split", 2, 30)   
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1,20, step=1)   
    max_features = trial.suggest_float("max_features", 0.3, 1.0)
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced", "balanced_subsample"])
    criterion = trial.suggest_categorical("criterion", ["gini", "entropy", "log_loss"])
    max_samples = trial.suggest_float("max_samples", 0.6, 1.0)
    

    
    params_rf_2 = {"n_estimators": n_estimators,
                'max_depth': max_depth,
              'min_samples_split': min_samples_split,
             'min_samples_leaf': min_samples_leaf,
              'max_features': max_features,
              'class_weight': class_weight,
              'criterion': criterion,
              'max_samples': max_samples
            }
    rf_pipe.set_params(**params_rf_2)

    
    # initiating cv
    score_rf_2 =  cross_val_score(estimator=rf_pipe, 
                             X=features_train, 
                             y=target_train, 
                             scoring=scoring["tpr_fpr_020"],
                             cv=cv,
                             n_jobs=-1).mean()
    
    return score_rf_2

# create a study (aim to maximize score) und setting a seed (random_state) for reproduceability
study_rf_2 = optuna.create_study(sampler=TPESampler(seed = 42), direction='maximize')

# perform hyperparamter tuning (while timing the process)
time_start = time.time()
# starting optimization process with our defined function and 50 iterations
study_rf_2.optimize(objective_rf_2, n_trials=50)
time_bayesian = time.time() - time_start

# store result in a data frame 
values_bayesian_rf_2 = [50, study_rf_2.best_trial.number, study_rf_2.best_trial.value, time_bayesian]
results_bayesian_rf_2 = pd.DataFrame([values_bayesian_rf_2], columns = ['Number of iterations', 
                                                                        'Iteration Number of Optimal Hyperparamters', 
                                                                        'Score', 
                                                                        'Time Elapsed (s)'])

[I 2026-09-25 13:26:33,421] A new study created in memory with name: no-name-266634af-56b2-435c-8fdf-2b06251099f3
[I 2026-09-25 13:36:32,132] Trial 0 finished with value: 0.9200840271602942 and parameters: {'n_estimators': 700, 'max_depth': 29, 'min_samples_split': 23, 'min_samples_leaf': 12, 'max_features': 0.40921304830970556, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.9879639408647978}. Best is trial 0 with value: 0.9200840271602942.
[I 2026-09-25 13:43:00,852] Trial 1 finished with value: 0.9086657909627356 and parameters: {'n_estimators': 1300, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 0.5129695700716763, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.7465447373174767}. Best is trial 0 with value: 0.9200840271602942.
[I 2026-09-25 13:53:07,240] Trial 2 finished with value: 0.9204433756365693 and parameters: {'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 11, 'max_features': 0.7146901982034297, 'class_weight': 'balanced', 'criterion': 'log_loss', 'max_samples': 0.9233589392465844}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 13:54:45,373] Trial 3 finished with value: 0.8609305229973325 and parameters: {'n_estimators': 600, 'max_depth': 6, 'min_samples_split': 21, 'min_samples_leaf': 9, 'max_features': 0.38542676439134516, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.8080272084711243}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 14:06:24,409] Trial 4 finished with value: 0.9002158677552339 and parameters: {'n_estimators': 1000, 'max_depth': 8, 'min_samples_split': 30, 'min_samples_leaf': 16, 'max_features': 0.9576492590949324, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.7301321323053057}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 14:11:33,413] Trial 5 finished with value: 0.9164877940344354 and parameters: {'n_estimators': 800, 'max_depth': 11, 'min_samples_split': 26, 'min_samples_leaf': 8, 'max_features': 0.49665415678116653, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.679486272613669}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 14:12:32,908] Trial 6 finished with value: 0.9092964190445396 and parameters: {'n_estimators': 300, 'max_depth': 26, 'min_samples_split': 22, 'min_samples_leaf': 15, 'max_features': 0.8398892426801621, 'class_weight': 'balanced', 'criterion': 'gini', 'max_samples': 0.6254233401144095}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 14:18:30,257] Trial 7 finished with value: 0.9154986258184463 and parameters: {'n_estimators': 700, 'max_depth': 12, 'min_samples_split': 23, 'min_samples_leaf': 13, 'max_features': 0.9210489198034286, 'class_weight': 'balanced_subsample', 'criterion': 'log_loss', 'max_samples': 0.7975182385457563}. Best is trial 2 with value: 0.9204433756365693.
[I 2026-09-25 14:21:29,559] Trial 8 finished with value: 0.9267356721364483 and parameters: {'n_estimators': 900, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.322000429980714, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9022204554172195}. Best is trial 8 with value: 0.9267356721364483.
[I 2026-09-25 14:25:48,818] Trial 9 finished with value: 0.8721675693153342 and parameters: {'n_estimators': 500, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.950788356639801, 'class_weight': 'balanced_subsample', 'criterion': 'log_loss', 'max_samples': 0.8157368967662603}. Best is trial 8 with value: 0.9267356721364483.
[I 2026-09-25 14:37:19,960] Trial 10 finished with value: 0.9226007194244605 and parameters: {'n_estimators': 1100, 'max_depth': 24, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 0.8570142058065098, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9838224762263869}. Best is trial 8 with value: 0.9267356721364483.
[I 2026-09-25 14:46:00,349] Trial 11 finished with value: 0.9213419287042276 and parameters: {'n_estimators': 1300, 'max_depth': 22, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 0.8378674852190751, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9461448674018147}. Best is trial 8 with value: 0.9267356721364483.
[I 2026-09-25 14:51:41,091] Trial 12 finished with value: 0.9299717888610461 and parameters: {'n_estimators': 1200, 'max_depth': 25, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.3562535590106859, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9346468785989636}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 14:54:40,043] Trial 13 finished with value: 0.9297922156656696 and parameters: {'n_estimators': 900, 'max_depth': 23, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.37611046472807946, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.972689907302161}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 14:58:02,156] Trial 14 finished with value: 0.9257468272572952 and parameters: {'n_estimators': 1500, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 0.32135520145368063, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.968166895423224}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 14:59:12,802] Trial 15 finished with value: 0.9274550561797753 and parameters: {'n_estimators': 300, 'max_depth': 26, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.32132931104096835, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9127104062575218}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:03:22,043] Trial 16 finished with value: 0.9209826610621615 and parameters: {'n_estimators': 1000, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 0.5258739037373834, 'class_weight': 'balanced', 'criterion': 'gini', 'max_samples': 0.8387483326529614}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:05:48,452] Trial 17 finished with value: 0.925477406838574 and parameters: {'n_estimators': 1300, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 0.3171446012635004, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9501210218726239}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:07:45,381] Trial 18 finished with value: 0.9251174116886265 and parameters: {'n_estimators': 1000, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 0.4785622499683727, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9623432696842562}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:09:54,209] Trial 19 finished with value: 0.9270052138064828 and parameters: {'n_estimators': 1200, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.423566885388808, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.7972834353944933}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:12:47,423] Trial 20 finished with value: 0.929342979548945 and parameters: {'n_estimators': 1100, 'max_depth': 24, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': 0.39524506884024657, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.9165151027939431}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:15:16,215] Trial 21 finished with value: 0.9294329480236035 and parameters: {'n_estimators': 800, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 0.42926937423816686, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.9634592832050821}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:17:53,198] Trial 22 finished with value: 0.9274551370139843 and parameters: {'n_estimators': 800, 'max_depth': 28, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.5171456831130627, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.9852834245845984}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:19:20,147] Trial 23 finished with value: 0.927994382022472 and parameters: {'n_estimators': 400, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 0.5739850419412447, 'class_weight': 'balanced_subsample', 'criterion': 'entropy', 'max_samples': 0.9320728325386103}. Best is trial 12 with value: 0.9299717888610461.
[I 2026-09-25 15:21:08,194] Trial 24 finished with value: 0.9305113572063698 and parameters: {'n_estimators': 800, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.4669194079631349, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.934606457910293}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:22:36,297] Trial 25 finished with value: 0.9296124808018753 and parameters: {'n_estimators': 700, 'max_depth': 26, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.42039797663687833, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8513461493438953}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:26:04,338] Trial 26 finished with value: 0.9281742381375798 and parameters: {'n_estimators': 1500, 'max_depth': 26, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.4891628056315444, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9118794811662384}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:27:09,692] Trial 27 finished with value: 0.9258366340635357 and parameters: {'n_estimators': 600, 'max_depth': 22, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 0.45620288823982386, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8689677146848704}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:29:23,741] Trial 28 finished with value: 0.9276348314606742 and parameters: {'n_estimators': 1300, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': 0.4015760853145501, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8905942144092325}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:30:41,055] Trial 29 finished with value: 0.9302416134508125 and parameters: {'n_estimators': 800, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 3, 'max_features': 0.3139735817078211, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9819182071057583}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:33:25,905] Trial 30 finished with value: 0.9270953843666639 and parameters: {'n_estimators': 1000, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 0.5464831284966216, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9736431188643269}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:34:54,951] Trial 31 finished with value: 0.9297025705278475 and parameters: {'n_estimators': 600, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5023003441786472, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9804097701538119}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:36:35,702] Trial 32 finished with value: 0.930241734702126 and parameters: {'n_estimators': 700, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 0.5137878961190316, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9002772693623444}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:38:30,040] Trial 33 finished with value: 0.926735672136448 and parameters: {'n_estimators': 700, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.6312042797813254, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8731609030418088}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:39:27,333] Trial 34 finished with value: 0.9288032495352032 and parameters: {'n_estimators': 700, 'max_depth': 29, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 0.34289295369854267, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8573726406334058}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:41:24,749] Trial 35 finished with value: 0.9292529706571822 and parameters: {'n_estimators': 800, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5149773968203668, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9148536634110945}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:42:12,311] Trial 36 finished with value: 0.9290729528736563 and parameters: {'n_estimators': 400, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 0.4036137997066458, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9961711644866331}. Best is trial 24 with value: 0.9305113572063698.
[I 2026-09-25 15:44:42,304] Trial 37 finished with value: 0.9309612399967666 and parameters: {'n_estimators': 600, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5894007264741322, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9465784758512832}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:46:48,159] Trial 38 finished with value: 0.9261066203217201 and parameters: {'n_estimators': 700, 'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 2, 'max_features': 0.6305524563656963, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9875632914166582}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:49:38,216] Trial 39 finished with value: 0.9295227144127395 and parameters: {'n_estimators': 700, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.6143772502198556, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9374393029025969}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:50:42,924] Trial 40 finished with value: 0.9289829035647885 and parameters: {'n_estimators': 700, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 0.31012598012169657, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9758476813063965}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:52:54,891] Trial 41 finished with value: 0.9289837927410881 and parameters: {'n_estimators': 600, 'max_depth': 25, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 0.5409872628112425, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9363989043397762}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:54:41,018] Trial 42 finished with value: 0.9307811413790315 and parameters: {'n_estimators': 800, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.43851347852279615, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9438851294022407}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:56:51,328] Trial 43 finished with value: 0.9300618785870179 and parameters: {'n_estimators': 1000, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.4602367102479647, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.8952909087047999}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 15:58:57,919] Trial 44 finished with value: 0.9275449034031201 and parameters: {'n_estimators': 900, 'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 0.48986066719269034, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9117689499565964}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 16:00:08,154] Trial 45 finished with value: 0.9307810201277181 and parameters: {'n_estimators': 700, 'max_depth': 29, 'min_samples_split': 3, 'min_samples_leaf': 1, 'max_features': 0.3482152702187764, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9437168889552934}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 16:02:57,468] Trial 46 finished with value: 0.9306021340231186 and parameters: {'n_estimators': 700, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.5789172478718557, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9985699801024256}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 16:04:53,125] Trial 47 finished with value: 0.9288035728720395 and parameters: {'n_estimators': 500, 'max_depth': 30, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 0.5796944787619823, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9761705936669524}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 16:05:59,140] Trial 48 finished with value: 0.9305112763721606 and parameters: {'n_estimators': 700, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.3122047173932194, 'class_weight': None, 'criterion': 'gini', 'max_samples': 0.9280408131964307}. Best is trial 37 with value: 0.9309612399967666.
[I 2026-09-25 16:08:08,250] Trial 49 finished with value: 0.9311410152776656 and parameters: {'n_estimators': 800, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.3838170996854309, 'class_weight': None, 'criterion': 'log_loss', 'max_samples': 0.9553039046686342}. Best is trial 49 with value: 0.9311410152776656.

In [147]:
# Ausgabe des Ergebnisses
results_bayesian_rf_2

,Number of iterations,Iteration Number of Optimal Hyperparamters,Score,Time Elapsed (s)
0,50,49,0.931,"9,694.861"

In [148]:
# Ausgabe der besten Parameter
study_rf_2.best_params

{'n_estimators': 800,
 'max_depth': 28,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 0.3838170996854309,
 'class_weight': None,
 'criterion': 'log_loss',
 'max_samples': 0.9553039046686342}

In [150]:
best_params_rf_2 = study_rf_2.best_params
rf_pipe_bo_2 = rf_pipe.set_params(
            n_estimators=best_params_rf_2["n_estimators"],
            max_depth=best_params_rf_2["max_depth"],
            min_samples_split=best_params_rf_2["min_samples_split"],
            min_samples_leaf=best_params_rf_2["min_samples_leaf"],
            max_features=best_params_rf_2["max_features"],
            class_weight=best_params_rf_2["class_weight"],
            criterion=best_params_rf_2["criterion"],
            max_samples=best_params_rf_2["max_samples"]
)

In [151]:
cv_rf_bo_2 = cross_val_score(estimator= rf_pipe_bo_2,
                            X=features_train,
                            y=target_train,
                            cv=cv,
                            scoring=scoring["tpr_fpr_020"],
                            n_jobs=-1)
#print(cv_log_reg_bo.mean())
print(f"CV Score: {cv_rf_bo_2.mean():.3f}")

CV Score: 0.931

Zum Vergleich: 

optimierte logistische Regression: 0.769

optminierte SVM: 0.916

optimierter RandomForest: 0.927

optimiertes neuronales Netz: 0.913